using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;

namespace Barotrauma.LuaCs.Data;

#region ModConfigurationInfo

[Serializable]
public readonly struct ModConfigData : IRunConfig
{
    public bool RunConfigLegacy { get; init; }
    public ContentPackage Package { get; init; }
    public string ModName { get; init; }
    
    
    public DependencyInfo[] Dependencies { get; init; }
    public AssemblyResourceInfo[] LoadableAssemblies { get; init; }
    public LocalizationResourceInfo[] LocalizationFiles { get; init; }

    public TargetRunMode RunModes { get; init; }
    
    public bool UseNonPublicizedAssemblies { get; }

    public bool AutoGenerated => false;
    public bool UseInternalAssemblyName { get; init; }

    public string Client
    {
        get
        {
            if (RunModes.HasFlag(TargetRunMode.ClientEnabled))
                return "Standard";
            if (RunModes.HasFlag(TargetRunMode.ClientAlways))
                return "Forced";
            return "None";
        }
    }
    
    public string Server 
    {
        get
        {
            if (RunModes.HasFlag(TargetRunMode.ServerEnabled))
                return "Standard";
            if (RunModes.HasFlag(TargetRunMode.ServerAlways))
                return "Forced";
            return "None";
        }
    }
    
    public bool IsForced()
    {
        throw new NotImplementedException();
    }

    public bool IsStandard()
    {
        throw new NotImplementedException();
    }

    public bool IsForcedOrStandard()
    {
        throw new NotImplementedException();
    }
}

#endregion

#region DataContracts

public readonly struct AssemblyResourceInfo : IAssemblyResourceInfo
{
    public string Name { get; init; }
    public bool IsScriptFile { get; init; }
    public bool LazyLoad { get; init; }
    public string Path { get; init; }
    public Platform SupportedPlatforms { get; init; }
    public Target SupportedTargets { get; init; }
}

public readonly struct DependencyInfo : IPackageDependencyInfo
{
    public string FolderPath { get; init; }
    public string PackageName { get; init; }
    public ulong SteamWorkshopId { get; init; }
    public ContentPackage DependencyPackage { get; init; }
}

public readonly struct LocalizationResourceInfo : ILocalizationResourceInfo
{
    public CultureInfo TargetCulture { get; init; }
    public ImmutableArray<string> FilePaths { get; init; }
    public Platform SupportedPlatforms { get; init; }
    public Target SupportedTargets { get; init; }
}

#endregion
