# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

env:
  CI_DIR: 717a3c49-f5dc-42eb-b332-fcf2988d00e3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          ref: ${{ inputs.target }}
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
        with:
          dotnet-version: |
            6.0.x

      - name: Run deploy script
        run: |
          set -e
          shopt -s globstar nullglob
          shopt -u dotglob
          cd Deploy
          git apply < ./patches/disable-interactivity.diff
          git apply < ./patches/prevent-crash-on-missing-dir.diff
          ./DeployAll.sh

      - name: Create tarball
        run: |
          mkdir -p "$CI_DIR"
          tar -czf "$CI_DIR/build.tar.gz" -C Deploy/bin/content .

      - name: Upload tarball
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
        with:
          name: build
          path: ${{ env.CI_DIR }}/build.tar.gz
